#define GLFW_INCLUDE_VULKAN
#include <GLFW/glfw3.h>
#include "ScopedTimer.h"
#include <fmt/format.h>
#include <iostream>
#include <memory>
#include <string>
#include <vector>
#include <algorithm>
#include <array>
#include <vulkan/vulkan.h>